/**
 * @file SequelizeModels
 * @author Jim Bulkowski <jim.b@paperelectron.com>
 * @project sequelize-core
 * @license MIT {@link http://opensource.org/licenses/MIT}
 */

import {CreatePlugin} from "@pomegranate/plugin-tools";
import {get, isFunction,map, reduce, capitalize, toLower} from 'lodash/fp'
const tsGenerator = `// Generated by the Pomegranate cli on {{creationDate}}

// name: {{name}}

import {Model} from '@pomofficial/sequelize-core'

export class {{upperName}} extends Model {
  public id!: number
  public name!: string
  public readonly createdAt!: Date;
  public readonly updatedAt!: Date;
  
  public static associate(models){
   
  }
}

export const SQLModel = (PluginLogger, Sequelize, SequelizeConnection) => {
  const Attributes = {
    id: {
      type: Sequelize.INTEGER,
      autoIncrement: true,
      primaryKey: true,
    },
    name: {
      type: Sequelize.STRING(1234)
    }
  }
  
  const Configuration = {
    modelName: '{{lowerName}}',
    sequelize: SequelizeConnection
  }

  {{upperName}}.init(Attributes, Configuration)

  return {{upperName}}
}
`

export const SequelizeModels = CreatePlugin('anything')
  .directories([{prop: 'main', path: '.'}])
  .configuration({
    name: 'SequelizeModels',
    injectableParam: 'SequelizeModels',
    injectableScope: 'application',
    depends: ['@pomofficial/SequelizeCore']
  })
  .hooks({
    load: async (Injector,PluginVariables, PluginFiles, PluginLogger) => {
      let files = await PluginFiles('main').fileList({ext: '.js'})
      return map((file) => {
        let required = require(file.path)
        let fileName = file.getBaseName()

        PluginLogger.log(`Found Model: ${fileName}.`, 2)

        let M = get('SQLModel', required)
        if (!M) {
          throw new Error(`Model file ${fileName} does not contain an export on the Model property.`)
        }
        if (!isFunction(M)) {
          throw new Error(`Model file ${fileName} does not export an injectable function on the Model property.`)
        }

        return [fileName, M]
      }, files)

    }
  })
  .commands(function (PomConfig, PluginFiles, Handlebars) {
    return (yargs) => {
      return yargs
        .usage('usage: $0')
        .command({
          command: 'generate <name>',
          aliases: 'g',
          describe: `Generates Model file <name>`,
          builder: (yargs) => {
            return yargs
              .positional('name', {
                describe: 'The the filename to be created.',
                default: 'index',
                type: 'string'
              })
              .option('l', {
                alias: 'language',
                describe: 'Generate TypeScript or Javascript',
                default: 'ts',
                choices: ['ts'],
                type: 'string'
              })
              .option('force', {
                alias: 'f',
                default: false,
                describe: 'overwrites the specified file if it exists.',
                type: 'boolean'
              })
          },
          handler: async (argv) => {
            let Pf = PluginFiles('main')
            let file = `${argv.name}.${argv.language}`
            let exists = await Pf.projectFileExists(file)
            let compile = Handlebars.compile(tsGenerator)
            let upperName = argv.name
            let lowerName = toLower(argv.name)
            let compiled = compile({
              creationDate: new Date().toDateString(),
              name: argv.name,
              upperName,
              lowerName
            })

            if (exists && !argv.force) {
              throw new Error(`${file} \n exists \n Rerun with --force to overwrite.`)
            }
            await Pf.outputProjectFile(file, compiled)
            console.log(`Created @pomofficial/SequelizeModels Model file ${file}`)
          }
        })
        .help()
    }
  })